DELETE FROM lexelite.lawyers WHERE email IN ('david@lexelite.com', 'sarah@lexelite.com', 'michael@lexelite.com', 'james@lexelite.com', 'aisha@lexelite.com', 'elena@lexelite.com');

INSERT INTO lexelite.lawyers 
(full_name, email, phone, password, specialization, qualification, experience, city, address, cnic_no, bio, consultation_fee, profile_image, status) VALUES 
('Zainab Tariq', 'zainab@lexelite.com', '03001234567', 'password123', 'Family Law', 'LLB from Punjab University', 8, 'Lahore', 'Gulberg III, Lahore', '35202-1234567-1', 'Experienced family lawyer dealing with Khula, child custody, and maintenance cases with sensitivity and care.', 5000.00, NULL, 'Approved'),
('Ali Hassan', 'ali@lexelite.com', '03331234567', 'password123', 'Criminal Law', 'JD from LUMS', 12, 'Karachi', 'DHA Phase 6, Karachi', '42201-1234567-3', 'Fierce criminal defense advocate specializing in bail matters, cybercrime, and trial cases.', 15000.00, NULL, 'Approved'),
('Fatima Shah', 'fatima@lexelite.com', '03211234567', 'password123', 'Corporate Law', 'LLM from University of London', 15, 'Islamabad', 'Blue Area, Islamabad', '61101-1234567-4', 'Expert in company registration, SECP compliance, and corporate litigation for startups and enterprises.', 25000.00, NULL, 'Approved'),
('Usman Qureshi', 'usman@lexelite.com', '03451234567', 'password123', 'Property Law', 'LLB from SM Law College', 20, 'Karachi', 'Clifton Block 5, Karachi', '42201-9876543-5', 'Veteran in real estate disputes, land grabbing cases, and property inheritance matters across Sindh.', 20000.00, NULL, 'Approved'),
('Bilal Ahmed', 'bilal@lexelite.com', '03111234567', 'password123', 'Civil Law', 'LLB (Hons) from University of Karachi', 10, 'Rawalpindi', 'Saddar, Rawalpindi', '37405-1234567-7', 'Dedicated civil litigation expert handling breach of contract, defamation, and rent controller disputes.', 10000.00, NULL, 'Approved'),
('Sana Malik', 'sana@lexelite.com', '03011234567', 'password123', 'Affidavit', 'BA LLB from Quaid-e-Azam University', 5, 'Lahore', 'Model Town, Lahore', '35201-1234567-2', 'Specialist in drafting legal documents, affidavits, agreements, and quick legal consultations.', 3000.00, NULL, 'Approved');
